### ISSUE TITLE
Document how to implement new Pulumi provider

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#902] opened 2019-02-19 23:42 UTC
Document the minimum steps of how to implement a new Pulumi provider (e.g. a _Foundation provider_ like AWS, openstack, etc).

**Comment by joeduffy** [comment] 2019-07-09 21:50
Dupe of https://github.com/pulumi/docs/issues/595.

**Closed by joeduffy** 2019-07-09 21:50 UTC
