### ISSUE TITLE
Run broken link checker on critical pages during PRs and pushes

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#2393] opened 2020-02-06 23:05 UTC
In #2100, we changed the broken link checker to run as a cron job rather than during PRs and pushes, due to it taking a long time to complete.

However, there are a core set of pages that it would be good to have broken link coverage on during PRs and pushes. For example, when updating the docs for a new release, it would be good to confirm that download links for each platform are working.

We should consider running the broken link checker on PRs and pushes for these critical pages (https://www.pulumi.com/docs/get-started/install/versions/ to start), but leave the vast remaining checks that take forever for the cron job.

**Comment by leezen** [comment] 2020-09-18 04:45
https://github.com/pulumi/docs/issues/2978 was a dupe of this w/o realizing it.

**Closed by leezen** 2020-09-18 04:45 UTC
