### ISSUE TITLE
Find and remove buckets script failing

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#11573] opened 2023-11-03 09:15 UTC
Regarding the merging of [this PR](https://github.com/pulumi/pulumi-hugo/pull/3554), I am seeing the `Find and remove buckets` [job failing](https://github.com/pulumi/pulumi-hugo/actions/runs/6742963133/job/18330259207). The last time I ran into this issue, I re-ran the failed job and it seemed to have resolved itself, but it didn't seem to work this time. Making this issue now because it's happened more than once.

Log error snippet:

```bash
delete: s3://pulumi-hugo-origin-pr-3554-87459bd3/yaml/index.html
remove_bucket: pulumi-hugo-origin-pr-3554-87459bd3

An error occurred (ParameterNotFound) when calling the DeleteParameter operation: 
make: *** [Makefile:54: ci-pull-request-closed] Error 254
Error: Process completed with exit code 2.
```

- [Full log file](https://github.com/pulumi/pulumi-hugo/files/13248459/github-logs-delete-buckets-failure.txt)

**Comment by cnunciato** [comment] 2024-07-01 22:21
Closing this as no longer reproducible (at least since migration to this repo).

**Closed by cnunciato** 2024-07-01 22:21 UTC
Labels: size/S, resolution/no-repro, kind/bug
