### ISSUE TITLE
Links for inputs in AWSX EC2Service don't go anywhere

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#7498] opened 2022-05-11 15:34 UTC
### Problem description

- I saw a product documentation issue on the following URL: https://www.pulumi.com/registry/packages/awsx/api-docs/ecs/ec2service/#inputs

The links for the `pulumiAws.types...` types don't go anywhere:

![image](https://user-images.githubusercontent.com/109047/167889712-f4c71ad2-c140-4504-b786-74e7e3dd4234.png)

**Comment by lukehoban** [comment] 2023-03-05 21:27
Duplicate of https://github.com/pulumi/registry/issues/210.

**Closed by lukehoban** 2023-03-05 21:27 UTC
Labels: area/docs, resolution/duplicate, kind/bug
