### ISSUE TITLE
Docs are missing for Python base packages

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1901] opened 2019-10-28 23:24 UTC
### Problem description

Documentation for resources, data sources, etc. from the base package of Pulumi providers (`pulumi_aws`, `pulumi_azure`, etc) are missing from the Python docs.

Specific examples:
- [`pulumi_aws.Provider`](https://github.com/pulumi/pulumi-aws/blob/fa6cb5f53da649626674e1e7fa742447506b0a19/sdk/python/pulumi_aws/provider.py#L12), [`pulumi_aws.get_availability_zones()`](https://github.com/pulumi/pulumi-aws/blob/fa6cb5f53da649626674e1e7fa742447506b0a19/sdk/python/pulumi_aws/get_availability_zones.py#L57), [`pulumi_aws.get_ami()`](https://github.com/pulumi/pulumi-aws/blob/fa6cb5f53da649626674e1e7fa742447506b0a19/sdk/python/pulumi_aws/get_ami.py#L246), etc. are missing from https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/.
- [`pulumi_azure.Provider`](https://github.com/pulumi/pulumi-azure/blob/549abc6ae363119f873932da063586008cbb07b7/sdk/python/pulumi_azure/provider.py#L12) is missing from https://www.pulumi.com/docs/reference/pkg/python/pulumi_azure/.
- [`pulumi_gcp.Provider`](https://github.com/pulumi/pulumi-gcp/blob/337c16e48261b6e803b0b4edc7bd5ea0189a5f1b/sdk/python/pulumi_gcp/provider.py#L12) is missing from https://www.pulumi.com/docs/reference/pkg/python/pulumi_gcp/.

**Comment by geekofalltrades** [comment] 2019-12-06 21:28
Also [pulumi-vault](https://www.pulumi.com/docs/reference/pkg/python/pulumi_vault/).

Compare to the [typescript doc](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/vault/) which has got those docs I crave.

**Comment by justinvp** [comment] 2020-01-15 02:58
Dupe of #1623

**Closed by justinvp** 2020-01-15 02:58 UTC
