### ISSUE TITLE
Consistently have up-to-date .NET API documentation

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#3514] opened 2020-06-07 23:18 UTC

**Comment by mikhailshilkov** [comment] 2020-06-08 06:00
Our original idea was to throw this out quickly and then measure/understand if people are actually using it and if these docs bring extra value compared to resource docs. If yes, we'd invest more into the user experience and up-to-date-ness.

Do we have any usage stats? Do we even measure?

**Comment by leezen** [comment] 2020-06-08 06:07
I have this currently as a 'punt' for the iteration. I think if we did want to invest more, we'll need to do the things you mention, e.g. measure and get some feedback. At the moment, we have neither (there's not even a GA tag on the pages). We should be able to get some CF data since it's behind the CDN, so I'll add that to my todo list so we can revisit this next iteration.

**Comment by leezen** [comment] 2020-06-10 05:56
```
SELECT "date", count(*) as cnt
FROM "default"."www_prod_cloudfront_logs" 
WHERE "date" > date('2020-05-01')
AND uri LIKE '/docs/reference/pkg/dotnet/%'
AND user_agent NOT LIKE '%bot%'
AND user_agent NOT LIKE '%Bot%'
AND user_agent NOT LIKE '%crawler%'
AND user_agent NOT LIKE '%Crawler%'
AND user_agent NOT LIKE '%webmaster%'
GROUP BY "date"
ORDER BY "date" DESC
```

date | cnt
-- | --
2020-06-10 | 220
2020-06-09 | 735
2020-06-08 | 597
2020-06-07 | 373
2020-06-06 | 227
2020-06-05 | 649
2020-06-04 | 485
2020-06-03 | 427
2020-06-02 | 593
2020-06-01 | 379
2020-05-31 | 261
2020-05-30 | 225
2020-05-29 | 434
2020-05-28 | 568
2020-05-27 | 696
2020-05-26 | 644
2020-05-25 | 350
2020-05-24 | 161
2020-05-23 | 245
2020-05-22 | 439
2020-05-21 | 435
2020-05-20 | 567
2020-05-19 | 483
2020-05-18 | 464
2020-05-17 | 198
2020-05-16 | 296
2020-05-15 | 462
2020-05-14 | 607
2020-05-13 | 437
2020-05-12 | 530
2020-05-11 | 568
2020-05-10 | 223
2020-05-09 | 544
2020-05-08 | 335
2020-05-07 | 727
2020-05-06 | 536
2020-05-05 | 823
2020-05-04 | 593
2020-05-03 | 348
2020-05-02 | 259

**Comment by thoward** [comment] 2024-10-29 21:55
Closing this as it seems to be a duplicate of https://github.com/pulumi/docs/issues/8800

**Closed by thoward** 2024-10-29 21:55 UTC
Labels: area/docs, kind/enhancement, resolution/duplicate, grooming-q2y25
