### ISSUE TITLE
Versioned API docs links

### ISSUE THREAD

**Issue by akashagarwal7** [pulumi/docs#6789] opened 2021-11-11 05:36 UTC
### Problem description

Do the API docs' links support adding the version identifier? If not, this would be really handy for creating references to the source of specs easily. For e.g.:
```
https://www.pulumi.com/registry/packages/gcp/api-docs/v5.26.0/monitoring/alertpolicy
```

The same would apply to the current/latest docs version too, with 'latest' being a synonym for the latest version.

### Affected area/feature

Docs.

**Comment by susanev** [comment] 2021-11-11 15:27
thank you for opening the issue!
we also have https://github.com/pulumi/docs/issues/2289

**Comment by akashagarwal7** [comment] 2021-11-12 00:17
@susanev correct! Happy to close this one in favour of that.

**Comment by leezen** [comment] 2021-11-12 14:17
Thanks for confirming and will close as a dupe of #2289

**Closed by leezen** 2021-11-12 14:17 UTC
Labels: kind/enhancement, resolution/duplicate
