### ISSUE TITLE
Webhooks page screenshot needs updating

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#6522] opened 2021-09-28 21:10 UTC
### Problem description

The screenshot on the [webhooks page](https://www.pulumi.com/docs/intro/console/webhooks/) shows an older version of the console 

![image.png](https://user-images.githubusercontent.com/109047/135165981-3a1d15c9-80f9-48a4-8c49-0858441f9483.png)

**Comment by susanev** [comment] 2021-09-28 21:15
thix @pierskarsenbarg!

these kind of issues should be opened in pulumi-hugo
and also i already have this https://github.com/pulumi/pulumi-hugo/issues/347, would you mind adding a comment there instead?

ill try and do it this week

**Comment by pierskarsenbarg** [comment] 2021-09-28 21:16
Got it. I'll add the comment now

**Comment by leezen** [comment] 2021-09-29 16:32
Closing as a duplicate of pulumi/pulumi-hugo#347 per the earlier comment.

**Closed by leezen** 2021-09-29 16:32 UTC
Labels: docs/cloud-console, resolution/duplicate, kind/bug
