### ISSUE TITLE
Be explicit about version of .NET framework required for csharp templates

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#4780] opened 2020-12-11 01:51 UTC
### Problem description

I'm updating our getting started tutorials and ran into the problem described here: https://github.com/pulumi/pulumi/issues/5913 

Currently, our docs say that you need .NET core 3.1 **or later**, but if you're starting from a clean machine and create a new project using one of our csharp templates (like `azure-csharp` or `gcp-csharp`), the latest version of .NET (5.0) will be installed on your machine, which then gives you the following error when running `pulumi up`:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
      - The following frameworks were found:
          5.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
      - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=osx.11.0-x64
 
error: an unhandled error occurred: Program exited with non-zero exit code: 150
```

So after I downloaded .NET core 3.1, everything worked as expected. Note: I also tried just changing the target framework to `net5.0` and that seemed to work as well.

### Suggestions for a fix

I think the best course of action short-term is to be very explicit in the docs that you need to install .NET Core 3.1 and update the text accordingly (rather than telling people to mess with the target framework for their project). Whenever we're ready to move the target framework up, we can update the docs.

**Comment by lukehoban** [comment] 2020-12-11 02:21
@mikhailshilkov what is our actual support matrix on .NET versions?  If it's a bug that we don't work on 5.0, I'd love to fix that. But if it's truly not supported and won't be for some time - then we will need to change our statement of supported versions in several places.

**Comment by mikhailshilkov** [comment] 2020-12-11 06:26
We support both .NET Core 3.1 and .NET 5. The issue is that we need to set the correct value in the `xproj` file. Related: https://github.com/pulumi/pulumi/issues/5913

**Comment by lukehoban** [comment] 2020-12-11 06:44
> The issue is that we need to set the correct value in the xproj file. Related: pulumi/pulumi#5913

Is that something we can fix imminently?  Or should we make a docs change to indicate we don't support .NET 5?

**Comment by mikhailshilkov** [comment] 2020-12-11 06:47
We should definitely fix this and support .NET 5. We likely need to detect the framework version or ask the user during `pulumi new`.

**Comment by thoward** [comment] 2024-11-13 08:03
Looking over this, this is less of a documentation issue, and more of a product issue, largely related to templates and hardcoding the .NET versions in csproj/fsproj files.

In short, the users run into problems when a .xsproj specifies a .NET version that is inconsistent with the framework version(s) they have installed. Our [.NET documentation](https://www.pulumi.com/docs/iac/languages-sdks/dotnet/) currently states that you can use "any supported version" (which at the moment is .NET 8/9) however, it's also true that Pulumi will happily execute and run .NET 6 code, if the framework is available and the .csproj specifies that. 

It's a constantly moving target, which depends on a variety of moving parts: 
- what language features pulumi depends on
- what versions are currently in support and available for installation
- what versions are currently hardcoded into our templates/examples csproj files
- what version a user happens to have on their machine

We recently updated our templates to specify .NET 8, but a user could easily have .NET 9 installed right now and run into this exact issue. It's also true that any of those templates would happily run on .NET 6 if you just change the target framework version in the csproj, but would fail if .NET 6 was the only version you had installed, and the csproj specified 8 or 9. 

Meanwhile, our SDK [specifies .NET 6](https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi/Pulumi.csproj#L4C23-L4C29), and our GitHub automation tests against both .NET 6 and .NET 8, but not 7 or 9...

So, at a product level, there is not really a specific version of .NET that is applicable for all scenarios, and what is *required* isn't very simple to define because of that. This will always be a moving target. I think instead, we should have some more nuanced guidance in the .NET docs that explains these issues and helps a user troubleshoot getting the correct version installed for the situation they are in.

I am going to add a small section to the .NET docs on the topic then close this out.

**Closed** 2024-11-13 17:39 UTC
Labels: area/docs, kind/enhancement, grooming-q2y25
