### ISSUE TITLE
Errant vars in code samples

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3473] opened 2020-06-01 23:06 UTC
Many of our code samples include things like

* JS/TS: `var_s3_bucket_name`
* Python: `var['s3_bucket_name']`
* C#: `@var.s3_bucket_name`

For example, see [many of the examples here](https://www.pulumi.com/docs/reference/pkg/aws/iam/getpolicydocument/).

Is this because the source program uses config? If so, should we be emitting examples that use the Pulumi configuration system to read those variables?

As it stands, it leads to code that won't compile and can be confusing to users.

**Comment by lukehoban** [comment] 2020-06-01 23:36
This is more or less the same issue tracked in https://github.com/pulumi/tf2pulumi/issues/185.

There are two parts to this:
1. The examples are "incomplete" in that they reference variables that aren't defined in the example
2. The names that are generated are "weird" and look unnatural.

Part (1) is inherited from the upstream examples.  They are very frequently not complete and standalone pieces of code, and assume that some number of variables or other resources were defined outside of the example.  We could try to fix some or all of these, but for the same reason that the upstream examples chose to go the route of not being 100% complete code, it's likely that practically we will want to have some/many examples that do refer to things not explicitly present in the code example.  We could choose to emit `const s3_bucket_name = ...` or something similar to more explicitly indicate this piece is being left out.

Part (2) we should fix to have the code example read more "naturally" for users of each Pulumi language.

**Comment by lukehoban** [comment] 2023-10-31 17:17
Closing this out as a dupe of https://github.com/pulumi/pulumi-terraform-bridge/issues/1277 which covers the same thing (though the exact way it shows up has changed since this issue was opened).

**Closed by lukehoban** 2023-10-31 17:17 UTC
Labels: area/docs, resolution/duplicate, kind/bug, kind/codegen
