### ISSUE TITLE
Programming model docs not fully loading on mobile

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/docs#3601] opened 2020-06-16 15:41 UTC
Trying to view the programming model docs on my phone (pixel 1, chrome 83.0) and nothing after the `Declaring Infrastructure` header is loading. Does this repro for anyone else? 

https://www.pulumi.com/docs/intro/concepts/programming-model/#declaring-infrastructure

**Comment by lukehoban** [comment] 2020-11-17 01:08
Closing as dupe of https://github.com/pulumi/docs/issues/4580, and adding this as an explicit bullet to confirm there.

**Closed by lukehoban** 2020-11-17 01:08 UTC
