### ISSUE TITLE
Improve our meta descriptions

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1475] opened 2019-07-30 16:10 UTC
At the moment, we rely on Hugo's Content Summaries for most of our `<meta name="description">` tags. These can be quite lengthy and poor (and indeed, Moz flags many/most of them). We could probably make an improvement by reducing `summaryLength` to something more like `30`, rather than its default of `70` -- but even better would be to hand edit these, even if just using `<!--more-->`.

See https://github.com/pulumi/docs/pull/1472#pullrequestreview-268478451 and https://github.com/pulumi/docs/pull/1472#issuecomment-516473456 fore more background.

**Comment by erinhyperplane** [comment] 2019-07-30 16:33
beat me to it ;) Mark as WIP as i'll come up with a proposal this week for our meta descriptions.

**Comment by erinhyperplane** [comment] 2019-07-31 18:17
see #1487

**Comment by lukehoban** [comment] 2019-08-01 20:35
Is this a dupe of #1487?

**Comment by erinhyperplane** [comment] 2019-08-01 20:41
@lukehoban Yes.

**Closed** 2019-08-01 20:45 UTC
Labels: area/www
