### ISSUE TITLE
Quotes not working in .NET API pages

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#3823] opened 2020-07-24 23:58 UTC
### Problem description

Double quotes are represented as `&quot;` in the .NET API pages.

Example from https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Azure/Pulumi.Azure.Role.Assignment.html:

![image](https://user-images.githubusercontent.com/293763/88443835-c036df00-cdce-11ea-9a0f-028a12d006de.png)

**Comment by lukehoban** [comment] 2020-07-25 00:48
Also tracked in https://github.com/pulumi/docs/issues/3536, but this is clearer so will close that one out as dupe of this.

**Comment by clstokes** [comment] 2020-07-25 02:11
@lukehoban i promise I searched for prior issues. 😄

**Comment by lukehoban** [comment] 2021-05-06 19:14
This appears to be fixed.  

![Uploading Screen Shot 2021-05-07 at 5.14.16 AM.png…]()

**Closed** 2021-05-06 19:14 UTC
Labels: kind/bug, resolution/fixed
