### ISSUE TITLE
Configuration blocks are misplaced in API docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3025] opened 2020-04-20 01:23 UTC
In certain API docs, we have supporting structures documented inside the examples, rather than following the argument structure. For example, https://www.pulumi.com/docs/reference/pkg/aws/acm/certificate/:

![image](https://user-images.githubusercontent.com/3953235/79705509-c74bcf80-826a-11ea-93c0-e5c0c39426fd.png)

My expectation is that such blocks would come after the "Create a ... Resource" section.

**Comment by lukehoban** [comment] 2020-04-20 02:41
I believe this is a dupe of https://github.com/pulumi/pulumi-terraform-bridge/issues/159.

**Closed** 2020-05-15 02:25 UTC
