### ISSUE TITLE
@pulumi/cloud docs seems to be missing API types

### ISSUE THREAD

**Issue by pgavlin** [pulumi/docs#455] opened 2018-06-26 18:14 UTC
<img width="1680" alt="pulumi-cloud-docs" src="https://user-images.githubusercontent.com/1224093/41931111-f1e0acc8-7931-11e8-9c6b-0459b2624672.png">

I would have expected to see the definitions for `cloud.ServiceArguments`, `cloud.Container`, etc.

**Comment by joeduffy** [comment] 2018-06-27 14:33
Assigning to @lukehoban , not sure who he wants to own issues like this.

**Comment by swgillespie** [comment] 2018-06-27 17:04
This is probably a dupe of this: https://github.com/pulumi/docs/issues/400

**Comment by lukehoban** [comment] 2018-06-28 23:38
Closing as dupe.

**Closed by lukehoban** 2018-06-28 23:38 UTC
