### ISSUE TITLE
Azure Functions tutorial for Python shows tutorial for C#

### ISSUE THREAD

**Issue by matkarasiewicz** [pulumi/docs#3523] opened 2020-06-09 08:10 UTC
> Azure Functions created from raw deployment packages in C#.

File: [docs/tutorials/azure/azure-py-functions-raw.md](https://www.pulumi.com/docs/tutorials/azure/azure-py-functions-raw/)

**Comment by leezen** [comment] 2020-06-09 19:03
This is "by design" though we could probably clean up the description, so I'll leave this issue open to make that change. The example shows how to deploy a raw deployment package in C# (meaning the function to be deployed is written in C#). However, the Pulumi program for achieving this is written in Python (which if you click through on "View Code" you'll see in `__main__.py`)

**Comment by mikhailshilkov** [comment] 2020-07-07 08:21
The underlying example is now updated to Python. The tutorial will pick that up the next time we generate.

**Comment by mikhailshilkov** [comment] 2020-07-08 10:45
I'll close this issue as there's no remaining work to track other than a more frequent tutorial re-generation

**Closed by mikhailshilkov** 2020-07-08 10:45 UTC
