### ISSUE TITLE
FIFO queue example is wrong

### ISSUE THREAD

**Issue by MarcoPolo** [pulumi/docs#3083] opened 2020-04-24 00:33 UTC
File: [docs/reference/pkg/nodejs/pulumi/aws/sqs/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/sqs/)

should include adding a `name:` field that ends in ".fifo". like so
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const queue = new aws.sqs.Queue("queue", {
    contentBasedDeduplication: true,
    fifoQueue: true,
    name: "queue.fifo"
});
```

**Comment by lukehoban** [comment] 2020-11-14 23:24
Going to close this as a dupe of https://github.com/pulumi/pulumi-aws/issues/967 - we really need to fix that in the core library itself - there isn't an easy way to just patch the docs here (it's going to be about the same effort as to just fix the underlying issue).

**Closed by lukehoban** 2020-11-14 23:24 UTC
Labels: docs/autogenerated
