### ISSUE TITLE
AWS module docs are missing - applicationloadbalancing, elb, etc.

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1792] opened 2019-09-27 05:13 UTC
### Problem description

The AWS Node SDK has [`applicationloadbalancing`](https://github.com/pulumi/pulumi-aws/tree/master/sdk/nodejs/applicationloadbalancing), [`elasticloadbalancing`](https://github.com/pulumi/pulumi-aws/tree/master/sdk/nodejs/elasticloadbalancing), and [`elasticloadbalancingv2`](https://github.com/pulumi/pulumi-aws/tree/master/sdk/nodejs/elasticloadbalancingv2) modules, but these aren't present in the modules listing at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ and also aren't accessible at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/applicationloadbalancing/, etc.

![image](https://user-images.githubusercontent.com/293763/65743508-bc043d00-e0a9-11e9-8931-217a4489dc9d.png)

**Comment by lukehoban** [comment] 2020-11-14 04:52
These docs *are* listed in the non-canonical resource docs.  This issue only exists for the JavaScript-specific content. It is likely related to https://github.com/pulumi/docs/issues/1527#issuecomment-529046190.

**Comment by cwinters8** [comment] 2021-03-28 17:59
What are `non-canonical resource docs` and where would I find them? I'm looking for awsx.elasticloadbalancingv2 docs and am not seeing any under the [awsx API docs](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/#). I'm not blocked currently but it would be nice to know about the different options available.

**Comment by lukehoban** [comment] 2021-03-29 01:36
> What are non-canonical resource docs and where would I find them?
Apologies - that was a typo - and intended to say "now-canonical".

The primary docs for theses AWS resources are at https://www.pulumi.com/docs/reference/pkg/aws/.

<img width="1763" alt="Screen Shot 2021-03-29 at 12 32 54 PM" src="https://user-images.githubusercontent.com/223467/112776285-fb3e9000-908a-11eb-84b5-c6e3aa8a5905.png">

>  I'm looking for awsx.elasticloadbalancingv2 docs and am not seeing any under the awsx API docs. 

Note that `awsx` is a different package than `aws`.   The `elasticloadbalancingv2` module is available also at `lb`, which is where the documentation exists.  The older name will likely be removed.

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/lb/

Both the originally reported issue in `aws`, and this issue that the namespace in `awsx` is not listed under its alternative name are due to https://github.com/pulumi/docs/issues/1527#issuecomment-529046190, so I will close this out as a dupe of that.

**Closed** 2021-03-29 01:37 UTC
Labels: kind/bug, resolution/duplicate
