### ISSUE TITLE
DistributionOrigin.domain_name may need to be camelCased

### ISSUE THREAD

**Issue by mowat27** [pulumi/docs#3763] opened 2020-07-11 15:25 UTC
File: [docs/reference/pkg/aws/cloudfront/distribution.md](https://www.pulumi.com/docs/reference/pkg/aws/cloudfront/distribution/)

Not sure is this is right or not but the domain_name parameter on DistributionOrigin is snake cased when everything else is camel cased.  I went ahead and camel cased it too and my program worked so I don't know if it works in its snake cased form.

**Comment by leezen** [comment] 2020-07-11 22:57
Dupe of https://github.com/pulumi/pulumi/issues/3151

**Closed by leezen** 2020-07-11 22:57 UTC
