### ISSUE TITLE
Being able to filter Azure native API documentation by version

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5374] opened 2021-03-01 03:29 UTC
Not sure if this could be more broadly applied, but it would be great to filter the Azure native API ref documentation by version so that you're only seeing resources that apply to that version. 

Here's the original request from a community member: https://pulumi-community.slack.com/archives/CB36DSVSA/p1614254629008500?thread_ts=1613784279.000300&cid=CB36DSVSA

**Comment by lukehoban** [comment] 2021-06-30 01:40
Duplicate of https://github.com/pulumi/docs/issues/2289.

**Closed by lukehoban** 2021-06-30 01:40 UTC
Labels: docs/api, kind/enhancement, resolution/duplicate
