### ISSUE TITLE
Document about how to implement own plugins

### ISSUE THREAD

**Issue by Aya-Yang** [pulumi/docs#1846] opened 2019-10-11 02:42 UTC
I read the docs, but I can't find the tutorials to implement a custom plugin, such as Resource Provider.

**Comment by leezen** [comment] 2020-02-18 19:07
Thanks for the feedback. You may find this blog post helpful depending on what you're trying to do: https://www.pulumi.com/blog/dynamic-providers/

**Comment by lukehoban** [comment] 2020-11-14 04:52
Closing as dupe of https://github.com/pulumi/docs/issues/595.

**Closed by lukehoban** 2020-11-14 04:52 UTC
