### ISSUE TITLE
Validate links to pages on site

### ISSUE THREAD

**Issue by sean1588** [pulumi/docs#7518] opened 2022-05-16 18:04 UTC
Explore running the link checker to validate links to pages on the site in order to catch links that may be broken. Maybe this can be some automated test that runs on a cadence (e.g. 6am, 6pm) to report broken links if there are any.

**Comment by cnunciato** [comment] 2022-05-16 20:00
We do run this daily (https://github.com/pulumi/docs/actions/workflows/check-links.yml), but it's unfortunately still failing; I haven't successfully gotten to the bottom of where the issue is yet (though have spent a good bit of time with it off and on over the last couple of months).

**Comment by susanev** [comment] 2022-05-16 20:05
@cnunciato this came up because it seems as though we have had a larger influx of community reports of 404s. is there any way to adjust that check to better service new 404s?

**Comment by cnunciato** [comment] 2022-05-21 14:32
Closing this as the link checker was reinstated with https://github.com/pulumi/docs/pull/7541 (and is back on the daily schedule as before).

**Closed by cnunciato** 2022-05-21 14:32 UTC
Labels: kind/engineering, resolution/fixed
