### ISSUE TITLE
change url gcp service account

### ISSUE THREAD

**Issue by krystian-kulgawczuk-pr** [pulumi/docs#2916] opened 2020-04-13 13:18 UTC
File: [docs/reference/pkg/gcp/serviceAccount/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/)

https://www.pulumi.com/docs/reference/pkg/gcp/serviceAccount/ -> https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/

**Comment by stack72** [comment] 2020-04-13 15:32
Hi @krystian-kulgawczuk-pr 

Thanks so much for raising the issue here - we are tracking this issue in #2837 

So I am going to close this as a duplicate of that issue and we will look at fixing it there

Paul

**Closed by stack72** 2020-04-13 15:32 UTC
