### ISSUE TITLE
Add docs ratings up/downvotes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1604] opened 2019-08-21 21:54 UTC
We often get feedback about "our docs," but it's not always clear which specific docs it applies to. We suspect it could be centered around very specific pages or entire subsections of the website (like our API docs). To make this easier to grok and track over time, let's add a :+1:/:-1: rating system (or stars, etc ⭐️ ).

**Comment by justinvp** [comment] 2020-01-15 02:56
Dupe of #2223

**Closed by justinvp** 2020-01-15 02:56 UTC
