### ISSUE TITLE
Bad formatting on `azure-native.keyvault.Vault`

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/docs#9820] opened 2023-09-12 17:39 UTC
https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/vault/

See the Go example, looks like there's some formatting issues

**Comment by cnunciato** [comment] 2024-02-05 20:48
Duplicate of https://github.com/pulumi/pulumi-azure-native/issues/2990.

**Closed by cnunciato** 2024-02-05 20:48 UTC
Labels: area/docs, resolution/duplicate, kind/codegen
