### ISSUE TITLE
The sample code does not compile

### ISSUE THREAD

**Issue by jfjcn** [pulumi/docs#5022] opened 2021-01-26 05:41 UTC
There is an issue on the RoutingRules->RoutingRulesArgs->RouteConfiguration value.

File: [docs/reference/pkg/azure-nextgen/network/frontdoor.md](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/network/frontdoor/)

**Comment by susanev** [comment] 2021-01-26 05:44
also tracked here: https://github.com/pulumi/pulumi-azure-nextgen/issues/210

**Comment by mikhailshilkov** [comment] 2021-01-26 07:17
Dupe of https://github.com/pulumi/pulumi-azure-nextgen/issues/210

**Closed by mikhailshilkov** 2021-01-26 07:17 UTC
