### ISSUE TITLE
Crosswalk landing page is blank

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2631] opened 2020-03-11 21:51 UTC
https://www.pulumi.com/crosswalk/ yields:

![image](https://user-images.githubusercontent.com/3953235/76467783-a2c92180-63a7-11ea-8e08-70afc37d41cd.png)

At the very least, should probably redirect to https://www.pulumi.com/crosswalk/aws, but given that we also have https://www.pulumi.com/crosswalk/kubernetes, we may want more of a menu.

**Comment by clstokes** [comment] 2020-03-18 00:38
Dupe of https://github.com/pulumi/docs/issues/2255

**Closed by clstokes** 2020-03-18 00:38 UTC
