### ISSUE TITLE
Issue with Datadog dashboard example

### ISSUE THREAD

**Issue by mattstratton** [pulumi/docs#6906] opened 2021-12-02 14:38 UTC
On https://www.pulumi.com/registry/packages/datadog/api-docs/dashboard/, in chrome (at least) the page takes a long time to render and then reloads. I think this is because the example code is very long compared to others?

Also, the example code includes references to "Created using the Datadog provider in Terraform" which we might want to change :)

**Comment by stack72** [comment] 2021-12-02 14:42
Closing as a dupe of #4703

**Closed by stack72** 2021-12-02 14:42 UTC
Labels: resolution/duplicate, kind/bug
