### ISSUE TITLE
Break up Programming Model docs into multiple pages

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#3249] opened 2020-05-11 12:40 UTC
The Programming Model docs are lengthy and can be hard to navigate through so it would be beneficial to break the docs up into multiple pages. 

Suggested breakup / ordering: 
- Pulumi Basics: Project / Program / Stack / Structure / Declaring Infra
- Resources (Maybe include this in Basics)
- Inputs and Outputs
- Config / Secrets
- Stack: Stack Outputs / Stack References
- Components 
- Providers 
- Runtime Functions 

The ordering has also been updated to represent a more natural progression, most common/used concepts first. This is a nice to have, risk is disruption with familiarity with current flow, happy to default back to current ordering.

**Comment by lukehoban** [comment] 2020-11-17 01:08
Closing as dupe of newly opened https://github.com/pulumi/docs/issues/4580.

**Closed by lukehoban** 2020-11-17 01:08 UTC
