### ISSUE TITLE
Remove `$` from commands with no output

### ISSUE THREAD

**Issue by ekrengel** [pulumi/docs#965] opened 2019-04-03 04:59 UTC
Some of the examples have $ at the beginning. These make it a bit harder to just copy & paste the snippet. Markdown linters suggest the `$` should only be present when the code snippet also includes output. We should update all docs to be consistent and only have `$` when output is included.

Nice to have: It would also be nice to have “Click to copy” buttons on example code.

**Comment by nesl247** [comment] 2019-07-11 17:03
This seems like a duplicate of #1024

**Closed** 2019-07-13 19:04 UTC
