### ISSUE TITLE
Missing resources in GCP API documentation

### ISSUE THREAD

**Issue by cloudcalvin** [pulumi/docs#4514] opened 2020-11-03 20:12 UTC
File: [docs/reference/pkg/gcp/cloudfunctions/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/cloudfunctions/)

It seems like some of the Resources are not listed on the page, such as CallbackFunction and HttpCallbackFunction for example.

**Comment by komalali** [comment] 2020-11-05 19:32
Dupe of https://github.com/pulumi/pulumi/issues/4785, tracking there

**Closed by komalali** 2020-11-05 19:32 UTC
